Replace init ETA by data-attribute to JSON format
viivue/easy-tab-accordion pull request #24
Opened 2022-12-16 03:30 UTC by vuquangpham

We can init ETA with options by using JSON format in container attribute:

```html
    <div data-eta='{ "id":"my-id", "animation":"slide", "hash":"false", "duration":100}'>
        
        <div>
            <button data-eta-trigger="section-1">Section 1</button>
            <div data-eta-receiver="section-1">Content</div>
        </div>

        
        <div>
            <button data-eta-trigger="section-2">Section 2</button>
            <div data-eta-receiver="section-2">Content</div>
        </div>
    </div>
```

2022-12-16 09:02 UTC, phucbm requested changes
Set ID via JSON seems not to work. Please check.

2022-12-19 10:37 UTC, phucbm commented on src/helpers.js
> -        delete options['id'];
Who put this line here at the beginning? Looks kind of a new thing to me.

2022-12-19 10:37 UTC, phucbm reviewed
Just a minor question left.

2022-12-21 07:57 UTC, phucbm approved these changes
LGTM.

2022-12-21 07:58 UTC, phucbm commented
Need update for demo and README.

2022-12-21 08:04 UTC, vuquangpham commented
> Need update for demo and README.

I have updated it, please check again! Thanks.

2022-12-21 10:14 UTC, phucbm approved these changes
LGTM.

2022-12-21 10:14 UTC, merged