Add hasActivatedSection flag
viivue/easy-tab-accordion pull request #40
Opened 2023-04-13 08:34 UTC by vuquangpham

## Problem
- We are unable to open multiple sections (`activeSections`) in the array.

## Why
![image](https://user-images.githubusercontent.com/30406982/231701893-663e1435-94e7-4a9b-88a8-eb6fc41a9736.png)
We have a condition for blocking  to avoid the double click on the animating item, but we need to escape that condition if we input `activeSections` in the array by default

## Problem
- Add `hasActivated` flag for checking it in `getToggleState` function.

2023-04-17 06:38 UTC, phucbm commented
> We are unable to open multiple sections (activeSections) in the array.

1. Could you link the source code that you're talking about here? And why should we need to be able to "open multiple sections"?

> but we need to escape that condition if we input activeSections in the array by default

2. Why do we need this? 

I don't understand what are you trying to achieve here!

2023-05-08 07:52 UTC, phucbm commented
Please merge this branch into branch `2.1.7`.

2023-05-15 03:28 UTC, phucbm commented on src/_index.js
> +        this.hasActivatedSection = true;
What's the point of line 145 when you override the value immediately here?

2023-05-15 03:28 UTC, phucbm requested changes
Please check my comments.

2023-05-15 05:32 UTC, vuquangpham commented
> > We are unable to open multiple sections (activeSections) in the array.
> 
> 1. Could you link the source code that you're talking about here? And why should we need to be able to "open multiple sections"?
> 
> > but we need to escape that condition if we input activeSections in the array by default
> 
> 2. Why do we need this?
> 
> I don't understand what are you trying to achieve here!

Because we already have these options but we can't use it
![image](https://github.com/viivue/easy-tab-accordion/assets/30406982/14c401ae-3bb8-4692-bd34-9c87b62ae0c2)

2023-05-17 06:24 UTC, phucbm commented
@vuquangpham I was talking about this one https://github.com/viivue/easy-tab-accordion/pull/40#discussion_r1193293290

2023-06-19 04:22 UTC, phucbm commented
@vuquangpham Any updates?

2023-06-20 03:55 UTC, vuquangpham commented
@phucbm 
I have renamed the variable. Could you please check it again! Many thanks.

2023-06-20 08:47 UTC, phucbm approved these changes
LGTM.

2023-06-20 08:48 UTC, merged